server:
  port: 20600

spring:
  application.name: subscription-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: angularpay
      username: service_account
      password: service_account_password
      authentication-database: angularpay

angularpay:
  pageSize: 50
  googleRecaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key: 6LezoUEdAAAAAOhJMDU1X6juxzPsB9bHXcYUfCXe
    secret: 6LezoUEdAAAAAHCOJapAxFZxrNgKxF6J29Lp87Jk
    threshold: 0.7
    enabled: true
  redis:
    host: localhost
    port: 6379
    timeout: 10000
